<?php

namespace AppBundle\Repository;

/**
 * PasteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasteRepository extends \Doctrine\ORM\EntityRepository
{
}
